# Generated by Django 4.1.7 on 2023-05-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0002_alter_location_latitude_alter_location_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupants', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=23, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=23, max_digits=25)),
                ('floor', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
