# Generated by Django 4.1.7 on 2023-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0005_alter_location_latitude_alter_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='office',
            name='floor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='office',
            name='occupants',
            field=models.CharField(max_length=100),
        ),
    ]
